version: "3.3"

services:
  django52:
    build:
      context: .
      args:
        DJANGO: ">=5.2,<5.3"
    command: ["runserver", "0.0.0.0:8000"]
    stdin_open: true
    tty: true
    ports:
      - "8005:8000"
    volumes:
      - .:/usr/src/django-bananas
      - ./example:/app
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "True"

  django60:
    build:
      context: .
      args:
        DJANGO: ">=6.0,<6.1"
    command: ["runserver", "0.0.0.0:8000"]
    stdin_open: true
    tty: true
    ports:
      - "8006:8000"
    volumes:
      - .:/usr/src/django-bananas
      - ./example:/app
    environment:
      PYTHONUNBUFFERED: "1"
      PYTHONDONTWRITEBYTECODE: "True"
